---
name: ci

on:  # yamllint disable-line rule:truthy
  push:
    branches:
    - main
  pull_request:

jobs:
  run:
    name: Compile and run
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: extractions/setup-just@v1
    - uses: yilinwei/setup-ammonite@master
      with:
        ammonite-version: 2.4.1
        scala-version: 2.13
    - run: just run-all
