---
name: ci

on:  # yamllint disable-line rule:truthy
  push:
    branches:
    - main
  pull_request:

jobs:
  run:
    name: Compile and run
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: extractions/setup-just@v1
    - run: sudo sh -c '(echo "#!/usr/bin/env sh" && curl -L https://github.com/com-lihaoyi/Ammonite/releases/download/2.4.1/2.13-2.4.1) > /usr/local/bin/amm && chmod +x /usr/local/bin/amm'
    - run: just run-all
